### ISSUE TITLE
Issue when downloading videos, AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by FreekCool** [JuanBindez/pytubefix#400]
# 🛑 DO NOT REMOVE OR SKIP THIS ISSUE TEMPLATE 🛑  
Issues with incomplete or missing information will be **closed automatically**.

---

## 🐞 **Bug Description**  
Provide a clear and concise description of the bug.  

Hi there, I am trying to download youtube videos in the lowest quality, as the code below shows. Only, for almost all videos I am having the following error:

```
Traceback (most recent call last):
  File "/my/path/my_python_file.py", line 266, in <module>
    download_youtube_video(video_link, LOCAL_VIDEOS_PATH, f'{video_id}.mp4', on_progress)
  File "/my/path/download_utils.py", line 159, in download_youtube_video
    ys = yt.streams.get_lowest_resolution()
  File "/my/path/python3.8/site-packages/pytubefix/__main__.py", line 649, in streams
    self.check_availability()
  File "/my/path/.local/lib/python3.8/site-packages/pytubefix/__main__.py", line 316, in check_availability
    status, messages = extract.playability_status(self.vid_info)
  File "/my/path/.local/lib/python3.8/site-packages/pytubefix/extract.py", line 106, in playability_status
    status_dict = player_response.get('playabilityStatus', {})
AttributeError: 'NoneType' object has no attribute 'get'
```
For example, this happens for a video with id qoTa_vfO8-4 and full link https://www.youtube.com/watch?v=qoTa_vfO8-4. The weird thing is that it works when I manually do it in the python3 terminal prompt. Also, these videos are not banned or only privately accessible. It is also worth noting that most of these videos come from Chinese content creators. 

---

## 🔢 **Code Snippet**  
Include the minimal code snippet that reproduces the issue.  

```python
import os
from pytubefix import YouTube
from pytubefix.cli import on_progress

def download_youtube_video(video_url, output_path, video_filename, on_progress):
    print(f'Download using po token')
    video_url = extract_video_url(video_url)
    print(f'Video URL: {video_url}')
    yt = YouTube(video_url, use_po_token=True, on_progress_callback = on_progress)
    ys = yt.streams.get_lowest_resolution()
    ys.download(output_path=output_path, filename=video_filename)

video_link = 'https://www.youtube.com/watch?v=qoTa_vfO8-4'

download_youtube_video(video_link, path, f'yourname.mp4', on_progress)
```

---

## 🎯 **Expected Behavior**  
Describe what you expected to happen instead of the observed behaviour.  

What would be expected is that this video is downloaded, like was done before. Only today this error started occuring. 

---

## 📸 **Screenshots or Logs**  
Error:
```
Traceback (most recent call last):
  File "/my/path/my_python_file.py", line 266, in <module>
    download_youtube_video(video_link, LOCAL_VIDEOS_PATH, f'{video_id}.mp4', on_progress)
  File "/my/path/download_utils.py", line 159, in download_youtube_video
    ys = yt.streams.get_lowest_resolution()
  File "/my/path/python3.8/site-packages/pytubefix/__main__.py", line 649, in streams
    self.check_availability()
  File "/my/path/.local/lib/python3.8/site-packages/pytubefix/__main__.py", line 316, in check_availability
    status, messages = extract.playability_status(self.vid_info)
  File "/my/path/.local/lib/python3.8/site-packages/pytubefix/extract.py", line 106, in playability_status
    status_dict = player_response.get('playabilityStatus', {})
AttributeError: 'NoneType' object has no attribute 'get'
```

---

## 🖥️ **Environment Details**  
Fill in the details below about your setup:  
- Ubuntu linux
- Python 3.8.10
- Pytubefix 8.9.0

---

## 📋 **Additional Context**  
Add any additional information or context that might help us resolve the issue.  

---
### 🚀 **Next Steps**  
Once submitted, we will triage the issue. Make sure to respond to follow-up questions to keep the process smooth.

**Comment by bigbear22941** [comment]
here the same...

` File "C:\Python37\Lib\site-packages\pytubefix\__main__.py", line 775, in length
    return int(self.vid_info.get('videoDetails', {}).get('lengthSeconds'))
                ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
 `

**Comment by NannoSilver** [comment]
I started to get the same error after upgraded Pytubefix from 8.8.1 to 8.10.

Potentially is an issue related to the way the Exceptions are handled in latest versions of pytubefix.
All the error cases I looked at were about videos not available in my region or not available at all.

For example:
The video https://www.youtube.com/watch?v=VicRV0Y187Q
Opening the video in the browser leads to `This live stream recording is not available.` error.

![image](https://github.com/user-attachments/assets/980cf9b5-8389-4ada-b03d-b987044c6d71)






Using pytubefix 8.8.1 raises the error `VicRV0Y187Q does not have a live stream recording available`
Using pytubefix 8.10 raises the error `'NoneType' object has no attribute 'get'`

The problem was fixed by downgrading pytubefix to version 8.8.1

**Comment by felipeucelli** [comment]
@NannoSilver 

You are right, the update that implemented fallback #397 clients was causing this error for videos that return `UNPLAYABLE`

I sent an update that fixes this, would you mind testing it #402

**Comment by NannoSilver** [comment]
> @NannoSilver
> 
> You are right, the update that implemented fallback #397 clients was causing this error for videos that return `UNPLAYABLE`
> 
> I sent an update that fixes this, would you mind testing it #402

I am running the https://github.com/JuanBindez/pytubefix/pull/402 patch in my production server at a couple of hours and seems the issue is fixed.
Thank you!

**Comment by felipeucelli** [comment]
@NannoSilver 

Try this patch and tell us the result #403

**Comment by NannoSilver** [comment]
> @NannoSilver
> 
> Try this patch and tell us the result #403

I am testing the https://github.com/JuanBindez/pytubefix/pull/403 patch in my production server for more than 24 hours. Since then the issue was no longer detected.
